// <auto-generated />
namespace Wan22ToolDesigner_WebView2
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            tabs = new TabControl();
            tabCreate = new TabPage();
            button4 = new Button();
            button2 = new Button();
            label1 = new Label();
            lblBalance = new Label();
            grpStatus = new GroupBox();
            lblStatus = new Label();
            prgStatus = new ProgressBar();
            lblElapsed = new Label();
            grpOutput = new GroupBox();
            txtGenerateResponse = new TextBox();
            lblVideoUrlTitle = new Label();
            txtOutputVideoUrl = new TextBox();
            btnDownloadAndOpen = new Button();
            grpPrompt = new GroupBox();
            txtPrompt = new TextBox();
            lblSeedTitle = new Label();
            numSeed = new NumericUpDown();
            btnClear = new Button();
            btnGenerate = new Button();
            grpVideo = new GroupBox();
            txtVideoPath = new TextBox();
            btnBrowseVideo = new Button();
            webView = new Microsoft.Web.WebView2.WinForms.WebView2();
            btnReplay = new Button();
            btnUploadVideo = new Button();
            lblVideoUploadedTitle = new Label();
            txtVideoUploadedUrl = new TextBox();
            lblUploadVideoStatus = new Label();
            grpImage = new GroupBox();
            txtImagePath = new TextBox();
            btnBrowseImage = new Button();
            picPreview = new PictureBox();
            btnUploadImage = new Button();
            lblImageUploadedTitle = new Label();
            txtImageUploadedUrl = new TextBox();
            lblUploadImageStatus = new Label();
            headerPanel = new Panel();
            lblRuntitle = new Label();
            BillHistoryTab = new TabPage();
            panelTop = new Panel();
            button5 = new Button();
            lblPageSize = new Label();
            numPageSize = new NumericUpDown();
            btnPrev = new Button();
            btnNext = new Button();
            btnReset = new Button();
            lblPage = new Label();
            lblTotal = new Label();
            grid = new DataGridView();
            tabSettings = new TabPage();
            button3 = new Button();
            button1 = new Button();
            label2 = new Label();
            txtDownloadPathBill = new TextBox();
            lblApiKey = new Label();
            txtApiKey = new TextBox();
            lblAccountId = new Label();
            txtAccountId = new TextBox();
            lblAccessToken = new Label();
            txtAccessToken = new TextBox();
            lblUploadUrl = new Label();
            txtUploadUrl = new TextBox();
            lblGenerateUrl = new Label();
            txtGenerateUrl = new TextBox();
            btnSaveConfig = new Button();
            pollTimer = new System.Windows.Forms.Timer(components);
            elapsedTimer = new System.Windows.Forms.Timer(components);
            animTitleTimer = new System.Windows.Forms.Timer(components);
            tabs.SuspendLayout();
            tabCreate.SuspendLayout();
            grpStatus.SuspendLayout();
            grpOutput.SuspendLayout();
            grpPrompt.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numSeed).BeginInit();
            grpVideo.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)webView).BeginInit();
            grpImage.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)picPreview).BeginInit();
            headerPanel.SuspendLayout();
            BillHistoryTab.SuspendLayout();
            panelTop.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)numPageSize).BeginInit();
            ((System.ComponentModel.ISupportInitialize)grid).BeginInit();
            tabSettings.SuspendLayout();
            SuspendLayout();
            // 
            // tabs
            // 
            tabs.Controls.Add(tabCreate);
            tabs.Controls.Add(BillHistoryTab);
            tabs.Controls.Add(tabSettings);
            tabs.Dock = DockStyle.Fill;
            tabs.Location = new Point(0, 0);
            tabs.Name = "tabs";
            tabs.SelectedIndex = 0;
            tabs.Size = new Size(1180, 920);
            tabs.TabIndex = 0;
            // 
            // tabCreate
            // 
            tabCreate.Controls.Add(button4);
            tabCreate.Controls.Add(button2);
            tabCreate.Controls.Add(label1);
            tabCreate.Controls.Add(lblBalance);
            tabCreate.Controls.Add(grpStatus);
            tabCreate.Controls.Add(grpOutput);
            tabCreate.Controls.Add(grpPrompt);
            tabCreate.Controls.Add(grpVideo);
            tabCreate.Controls.Add(grpImage);
            tabCreate.Controls.Add(headerPanel);
            tabCreate.Location = new Point(4, 24);
            tabCreate.Name = "tabCreate";
            tabCreate.Padding = new Padding(3);
            tabCreate.Size = new Size(1172, 892);
            tabCreate.TabIndex = 0;
            tabCreate.Text = "Tạo video";
            tabCreate.UseVisualStyleBackColor = true;
            // 
            // button4
            // 
            button4.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point);
            button4.ForeColor = Color.Firebrick;
            button4.Location = new Point(811, 8);
            button4.Name = "button4";
            button4.Size = new Size(140, 34);
            button4.TabIndex = 4;
            button4.Text = "Thoát";
            button4.Click += button4_Click;
            // 
            // button2
            // 
            button2.Location = new Point(957, 8);
            button2.Name = "button2";
            button2.Size = new Size(40, 34);
            button2.TabIndex = 8;
            button2.Text = "♻";
            button2.Click += button2_Click;
            // 
            // label1
            // 
            label1.AutoSize = true;
            label1.Location = new Point(1003, 27);
            label1.Name = "label1";
            label1.Size = new Size(96, 15);
            label1.TabIndex = 6;
            label1.Text = "Version: 0.102225";
            label1.Click += label1_Click;
            // 
            // lblBalance
            // 
            lblBalance.AutoSize = true;
            lblBalance.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point);
            lblBalance.Location = new Point(1003, 6);
            lblBalance.Name = "lblBalance";
            lblBalance.Size = new Size(55, 15);
            lblBalance.TabIndex = 0;
            lblBalance.Text = "Số dư: --";
            // 
            // grpStatus
            // 
            grpStatus.Controls.Add(lblStatus);
            grpStatus.Controls.Add(prgStatus);
            grpStatus.Controls.Add(lblElapsed);
            grpStatus.Location = new Point(9, 791);
            grpStatus.Name = "grpStatus";
            grpStatus.Size = new Size(1160, 80);
            grpStatus.TabIndex = 0;
            grpStatus.TabStop = false;
            grpStatus.Text = "Trạng thái xử lý";
            // 
            // lblStatus
            // 
            lblStatus.AutoSize = true;
            lblStatus.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point);
            lblStatus.Location = new Point(12, 32);
            lblStatus.Name = "lblStatus";
            lblStatus.Size = new Size(39, 21);
            lblStatus.TabIndex = 0;
            lblStatus.Text = "Idle";
            // 
            // prgStatus
            // 
            prgStatus.Location = new Point(249, 33);
            prgStatus.Name = "prgStatus";
            prgStatus.Size = new Size(620, 20);
            prgStatus.Style = ProgressBarStyle.Marquee;
            prgStatus.TabIndex = 1;
            prgStatus.Visible = false;
            // 
            // lblElapsed
            // 
            lblElapsed.AutoSize = true;
            lblElapsed.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold, GraphicsUnit.Point);
            lblElapsed.Location = new Point(902, 33);
            lblElapsed.Name = "lblElapsed";
            lblElapsed.Size = new Size(114, 21);
            lblElapsed.TabIndex = 2;
            lblElapsed.Text = "Elapsed: 00:00";
            // 
            // grpOutput
            // 
            grpOutput.Controls.Add(txtGenerateResponse);
            grpOutput.Controls.Add(lblVideoUrlTitle);
            grpOutput.Controls.Add(txtOutputVideoUrl);
            grpOutput.Controls.Add(btnDownloadAndOpen);
            grpOutput.Location = new Point(6, 562);
            grpOutput.Name = "grpOutput";
            grpOutput.Size = new Size(1160, 223);
            grpOutput.TabIndex = 1;
            grpOutput.TabStop = false;
            grpOutput.Text = "Log tạo video";
            // 
            // txtGenerateResponse
            // 
            txtGenerateResponse.Location = new Point(12, 26);
            txtGenerateResponse.Multiline = true;
            txtGenerateResponse.Name = "txtGenerateResponse";
            txtGenerateResponse.ReadOnly = true;
            txtGenerateResponse.ScrollBars = ScrollBars.Vertical;
            txtGenerateResponse.Size = new Size(1134, 140);
            txtGenerateResponse.TabIndex = 0;
            // 
            // lblVideoUrlTitle
            // 
            lblVideoUrlTitle.AutoSize = true;
            lblVideoUrlTitle.Location = new Point(15, 169);
            lblVideoUrlTitle.Name = "lblVideoUrlTitle";
            lblVideoUrlTitle.Size = new Size(64, 15);
            lblVideoUrlTitle.TabIndex = 1;
            lblVideoUrlTitle.Text = "Video URL:";
            // 
            // txtOutputVideoUrl
            // 
            txtOutputVideoUrl.Location = new Point(15, 189);
            txtOutputVideoUrl.Name = "txtOutputVideoUrl";
            txtOutputVideoUrl.ReadOnly = true;
            txtOutputVideoUrl.Size = new Size(965, 23);
            txtOutputVideoUrl.TabIndex = 2;
            // 
            // btnDownloadAndOpen
            // 
            btnDownloadAndOpen.Location = new Point(997, 189);
            btnDownloadAndOpen.Name = "btnDownloadAndOpen";
            btnDownloadAndOpen.Size = new Size(149, 23);
            btnDownloadAndOpen.TabIndex = 3;
            btnDownloadAndOpen.Text = "Tải & Mở";
            btnDownloadAndOpen.Click += btnDownloadAndOpen_Click;
            // 
            // grpPrompt
            // 
            grpPrompt.Controls.Add(txtPrompt);
            grpPrompt.Controls.Add(lblSeedTitle);
            grpPrompt.Controls.Add(numSeed);
            grpPrompt.Controls.Add(btnClear);
            grpPrompt.Controls.Add(btnGenerate);
            grpPrompt.Location = new Point(6, 416);
            grpPrompt.Name = "grpPrompt";
            grpPrompt.Size = new Size(1160, 140);
            grpPrompt.TabIndex = 2;
            grpPrompt.TabStop = false;
            grpPrompt.Text = "Prompt (tùy chọn)";
            // 
            // txtPrompt
            // 
            txtPrompt.Location = new Point(12, 26);
            txtPrompt.Multiline = true;
            txtPrompt.Name = "txtPrompt";
            txtPrompt.Size = new Size(860, 100);
            txtPrompt.TabIndex = 0;
            txtPrompt.Text = "The girl is dancing";
            // 
            // lblSeedTitle
            // 
            lblSeedTitle.AutoSize = true;
            lblSeedTitle.Location = new Point(884, 24);
            lblSeedTitle.Name = "lblSeedTitle";
            lblSeedTitle.Size = new Size(35, 15);
            lblSeedTitle.TabIndex = 1;
            lblSeedTitle.Text = "Seed:";
            // 
            // numSeed
            // 
            numSeed.Location = new Point(930, 22);
            numSeed.Maximum = new decimal(new int[] { 999999, 0, 0, 0 });
            numSeed.Minimum = new decimal(new int[] { 999999, 0, 0, int.MinValue });
            numSeed.Name = "numSeed";
            numSeed.Size = new Size(216, 23);
            numSeed.TabIndex = 2;
            numSeed.Value = new decimal(new int[] { 1, 0, 0, int.MinValue });
            // 
            // btnClear
            // 
            btnClear.Location = new Point(886, 52);
            btnClear.Name = "btnClear";
            btnClear.Size = new Size(262, 34);
            btnClear.TabIndex = 3;
            btnClear.Text = "Xóa dữ liệu";
            btnClear.Click += btnClear_Click;
            // 
            // btnGenerate
            // 
            btnGenerate.Location = new Point(886, 92);
            btnGenerate.Name = "btnGenerate";
            btnGenerate.Size = new Size(262, 34);
            btnGenerate.TabIndex = 4;
            btnGenerate.Text = "Tạo";
            btnGenerate.Click += btnGenerate_Click;
            // 
            // grpVideo
            // 
            grpVideo.Controls.Add(txtVideoPath);
            grpVideo.Controls.Add(btnBrowseVideo);
            grpVideo.Controls.Add(webView);
            grpVideo.Controls.Add(btnReplay);
            grpVideo.Controls.Add(btnUploadVideo);
            grpVideo.Controls.Add(lblVideoUploadedTitle);
            grpVideo.Controls.Add(txtVideoUploadedUrl);
            grpVideo.Controls.Add(lblUploadVideoStatus);
            grpVideo.Location = new Point(596, 50);
            grpVideo.Name = "grpVideo";
            grpVideo.Size = new Size(570, 360);
            grpVideo.TabIndex = 3;
            grpVideo.TabStop = false;
            grpVideo.Text = "1.b Video (bắt buộc) + Upload";
            // 
            // txtVideoPath
            // 
            txtVideoPath.Location = new Point(12, 26);
            txtVideoPath.Name = "txtVideoPath";
            txtVideoPath.ReadOnly = true;
            txtVideoPath.Size = new Size(320, 23);
            txtVideoPath.TabIndex = 0;
            // 
            // btnBrowseVideo
            // 
            btnBrowseVideo.Location = new Point(340, 25);
            btnBrowseVideo.Name = "btnBrowseVideo";
            btnBrowseVideo.Size = new Size(110, 30);
            btnBrowseVideo.TabIndex = 1;
            btnBrowseVideo.Text = "Chọn video…";
            btnBrowseVideo.Click += btnBrowseVideo_Click;
            // 
            // webView
            // 
            webView.AllowExternalDrop = true;
            webView.BackColor = Color.LightSteelBlue;
            webView.CreationProperties = null;
            webView.DefaultBackgroundColor = Color.LightSteelBlue;
            webView.Location = new Point(12, 64);
            webView.Name = "webView";
            webView.Size = new Size(438, 240);
            webView.TabIndex = 2;
            webView.ZoomFactor = 1D;
            // 
            // btnReplay
            // 
            btnReplay.Location = new Point(456, 25);
            btnReplay.Name = "btnReplay";
            btnReplay.Size = new Size(100, 34);
            btnReplay.TabIndex = 3;
            btnReplay.Text = "Replay";
            btnReplay.Click += btnReplay_Click;
            // 
            // btnUploadVideo
            // 
            btnUploadVideo.Location = new Point(456, 64);
            btnUploadVideo.Name = "btnUploadVideo";
            btnUploadVideo.Size = new Size(100, 34);
            btnUploadVideo.TabIndex = 4;
            btnUploadVideo.Text = "Upload video";
            btnUploadVideo.Click += btnUploadVideo_Click;
            // 
            // lblVideoUploadedTitle
            // 
            lblVideoUploadedTitle.AutoSize = true;
            lblVideoUploadedTitle.Location = new Point(160, 318);
            lblVideoUploadedTitle.Name = "lblVideoUploadedTitle";
            lblVideoUploadedTitle.Size = new Size(82, 15);
            lblVideoUploadedTitle.TabIndex = 5;
            lblVideoUploadedTitle.Text = "download_url:";
            lblVideoUploadedTitle.Visible = false;
            // 
            // txtVideoUploadedUrl
            // 
            txtVideoUploadedUrl.Location = new Point(260, 314);
            txtVideoUploadedUrl.Name = "txtVideoUploadedUrl";
            txtVideoUploadedUrl.Size = new Size(190, 23);
            txtVideoUploadedUrl.TabIndex = 6;
            txtVideoUploadedUrl.Visible = false;
            // 
            // lblUploadVideoStatus
            // 
            lblUploadVideoStatus.AutoSize = true;
            lblUploadVideoStatus.Location = new Point(12, 322);
            lblUploadVideoStatus.Name = "lblUploadVideoStatus";
            lblUploadVideoStatus.Size = new Size(25, 15);
            lblUploadVideoStatus.TabIndex = 7;
            lblUploadVideoStatus.Text = "......";
            // 
            // grpImage
            // 
            grpImage.Controls.Add(txtImagePath);
            grpImage.Controls.Add(btnBrowseImage);
            grpImage.Controls.Add(picPreview);
            grpImage.Controls.Add(btnUploadImage);
            grpImage.Controls.Add(lblImageUploadedTitle);
            grpImage.Controls.Add(txtImageUploadedUrl);
            grpImage.Controls.Add(lblUploadImageStatus);
            grpImage.Location = new Point(6, 50);
            grpImage.Name = "grpImage";
            grpImage.Size = new Size(570, 360);
            grpImage.TabIndex = 4;
            grpImage.TabStop = false;
            grpImage.Text = "1.a Ảnh (bắt buộc) + Upload";
            // 
            // txtImagePath
            // 
            txtImagePath.Location = new Point(12, 26);
            txtImagePath.Name = "txtImagePath";
            txtImagePath.ReadOnly = true;
            txtImagePath.Size = new Size(420, 23);
            txtImagePath.TabIndex = 0;
            // 
            // btnBrowseImage
            // 
            btnBrowseImage.Location = new Point(440, 25);
            btnBrowseImage.Name = "btnBrowseImage";
            btnBrowseImage.Size = new Size(110, 30);
            btnBrowseImage.TabIndex = 1;
            btnBrowseImage.Text = "Chọn ảnh…";
            btnBrowseImage.Click += btnBrowseImage_Click;
            // 
            // picPreview
            // 
            picPreview.BackColor = Color.LightSteelBlue;
            picPreview.Location = new Point(12, 64);
            picPreview.Name = "picPreview";
            picPreview.Size = new Size(420, 240);
            picPreview.SizeMode = PictureBoxSizeMode.Zoom;
            picPreview.TabIndex = 2;
            picPreview.TabStop = false;
            // 
            // btnUploadImage
            // 
            btnUploadImage.Location = new Point(440, 64);
            btnUploadImage.Name = "btnUploadImage";
            btnUploadImage.Size = new Size(110, 34);
            btnUploadImage.TabIndex = 3;
            btnUploadImage.Text = "Upload ảnh";
            btnUploadImage.Click += btnUploadImage_Click;
            // 
            // lblImageUploadedTitle
            // 
            lblImageUploadedTitle.AutoSize = true;
            lblImageUploadedTitle.Location = new Point(336, 317);
            lblImageUploadedTitle.Name = "lblImageUploadedTitle";
            lblImageUploadedTitle.Size = new Size(82, 15);
            lblImageUploadedTitle.TabIndex = 4;
            lblImageUploadedTitle.Text = "download_url:";
            lblImageUploadedTitle.Visible = false;
            // 
            // txtImageUploadedUrl
            // 
            txtImageUploadedUrl.Location = new Point(440, 314);
            txtImageUploadedUrl.Name = "txtImageUploadedUrl";
            txtImageUploadedUrl.Size = new Size(110, 23);
            txtImageUploadedUrl.TabIndex = 5;
            txtImageUploadedUrl.Visible = false;
            // 
            // lblUploadImageStatus
            // 
            lblUploadImageStatus.AutoSize = true;
            lblUploadImageStatus.Location = new Point(12, 322);
            lblUploadImageStatus.Name = "lblUploadImageStatus";
            lblUploadImageStatus.Size = new Size(25, 15);
            lblUploadImageStatus.TabIndex = 6;
            lblUploadImageStatus.Text = "......";
            // 
            // headerPanel
            // 
            headerPanel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            headerPanel.Controls.Add(lblRuntitle);
            headerPanel.Location = new Point(6, 6);
            headerPanel.Name = "headerPanel";
            headerPanel.Size = new Size(705, 40);
            headerPanel.TabIndex = 5;
            // 
            // lblRuntitle
            // 
            lblRuntitle.AutoSize = true;
            lblRuntitle.Font = new Font("Segoe UI Black", 15.75F, FontStyle.Bold, GraphicsUnit.Point);
            lblRuntitle.Location = new Point(3, 6);
            lblRuntitle.Name = "lblRuntitle";
            lblRuntitle.Size = new Size(524, 30);
            lblRuntitle.TabIndex = 7;
            lblRuntitle.Text = "CÔNG CỤ CHẠY WAN2.2 AI-ANIMATE - MRCHEN";
            // 
            // BillHistoryTab
            // 
            BillHistoryTab.Controls.Add(panelTop);
            BillHistoryTab.Controls.Add(grid);
            BillHistoryTab.Location = new Point(4, 24);
            BillHistoryTab.Name = "BillHistoryTab";
            BillHistoryTab.Padding = new Padding(3);
            BillHistoryTab.Size = new Size(1172, 892);
            BillHistoryTab.TabIndex = 3;
            BillHistoryTab.Text = "Lịch sử Bill";
            BillHistoryTab.UseVisualStyleBackColor = true;
            // 
            // panelTop
            // 
            panelTop.Controls.Add(button5);
            panelTop.Controls.Add(lblPageSize);
            panelTop.Controls.Add(numPageSize);
            panelTop.Controls.Add(btnPrev);
            panelTop.Controls.Add(btnNext);
            panelTop.Controls.Add(btnReset);
            panelTop.Controls.Add(lblPage);
            panelTop.Controls.Add(lblTotal);
            panelTop.Dock = DockStyle.Top;
            panelTop.Location = new Point(3, 3);
            panelTop.Margin = new Padding(3, 2, 3, 2);
            panelTop.Name = "panelTop";
            panelTop.Size = new Size(1166, 35);
            panelTop.TabIndex = 2;
            // 
            // button5
            // 
            button5.Location = new Point(994, 4);
            button5.Margin = new Padding(3, 2, 3, 2);
            button5.Name = "button5";
            button5.Size = new Size(156, 25);
            button5.TabIndex = 7;
            button5.Text = "Mở thư mục lưu video";
            button5.Click += button5_Click;
            // 
            // lblPageSize
            // 
            lblPageSize.AutoSize = true;
            lblPageSize.Location = new Point(10, 9);
            lblPageSize.Name = "lblPageSize";
            lblPageSize.Size = new Size(30, 15);
            lblPageSize.TabIndex = 0;
            lblPageSize.Text = "Size:";
            // 
            // numPageSize
            // 
            numPageSize.Location = new Point(50, 8);
            numPageSize.Margin = new Padding(3, 2, 3, 2);
            numPageSize.Minimum = new decimal(new int[] { 1, 0, 0, 0 });
            numPageSize.Name = "numPageSize";
            numPageSize.Size = new Size(61, 23);
            numPageSize.TabIndex = 1;
            numPageSize.Value = new decimal(new int[] { 10, 0, 0, 0 });
            // 
            // btnPrev
            // 
            btnPrev.Location = new Point(131, 6);
            btnPrev.Margin = new Padding(3, 2, 3, 2);
            btnPrev.Name = "btnPrev";
            btnPrev.Size = new Size(79, 25);
            btnPrev.TabIndex = 2;
            btnPrev.Text = "← Trước";
            btnPrev.Click += btnPrev_Click_2;
            // 
            // btnNext
            // 
            btnNext.Location = new Point(215, 6);
            btnNext.Margin = new Padding(3, 2, 3, 2);
            btnNext.Name = "btnNext";
            btnNext.Size = new Size(79, 25);
            btnNext.TabIndex = 3;
            btnNext.Text = "Sau →";
            btnNext.Click += btnNext_Click_1;
            // 
            // btnReset
            // 
            btnReset.Location = new Point(299, 6);
            btnReset.Margin = new Padding(3, 2, 3, 2);
            btnReset.Name = "btnReset";
            btnReset.Size = new Size(79, 25);
            btnReset.TabIndex = 4;
            btnReset.Text = "Reset";
            btnReset.Click += btnReset_Click_1;
            // 
            // lblPage
            // 
            lblPage.AutoSize = true;
            lblPage.Location = new Point(394, 9);
            lblPage.Name = "lblPage";
            lblPage.Size = new Size(49, 15);
            lblPage.TabIndex = 5;
            lblPage.Text = "Trang: 1";
            // 
            // lblTotal
            // 
            lblTotal.AutoSize = true;
            lblTotal.Location = new Point(472, 9);
            lblTotal.Name = "lblTotal";
            lblTotal.Size = new Size(46, 15);
            lblTotal.TabIndex = 6;
            lblTotal.Text = "Tổng: -";
            // 
            // grid
            // 
            grid.Location = new Point(3, 42);
            grid.Margin = new Padding(3, 2, 3, 2);
            grid.Name = "grid";
            grid.RowTemplate.Height = 29;
            grid.Size = new Size(1166, 847);
            grid.TabIndex = 3;
            grid.CellContentClick += gridBillHistory_CellContentClickAsync;
            grid.CellFormatting += grid_CellFormatting;
            // 
            // tabSettings
            // 
            tabSettings.Controls.Add(button3);
            tabSettings.Controls.Add(button1);
            tabSettings.Controls.Add(label2);
            tabSettings.Controls.Add(txtDownloadPathBill);
            tabSettings.Controls.Add(lblApiKey);
            tabSettings.Controls.Add(txtApiKey);
            tabSettings.Controls.Add(lblAccountId);
            tabSettings.Controls.Add(txtAccountId);
            tabSettings.Controls.Add(lblAccessToken);
            tabSettings.Controls.Add(txtAccessToken);
            tabSettings.Controls.Add(lblUploadUrl);
            tabSettings.Controls.Add(txtUploadUrl);
            tabSettings.Controls.Add(lblGenerateUrl);
            tabSettings.Controls.Add(txtGenerateUrl);
            tabSettings.Controls.Add(btnSaveConfig);
            tabSettings.Location = new Point(4, 24);
            tabSettings.Name = "tabSettings";
            tabSettings.Size = new Size(1172, 892);
            tabSettings.TabIndex = 2;
            tabSettings.Text = "API Settings";
            tabSettings.UseVisualStyleBackColor = true;
            // 
            // button3
            // 
            button3.Location = new Point(787, 230);
            button3.Name = "button3";
            button3.Size = new Size(133, 30);
            button3.TabIndex = 14;
            button3.Text = "Sử dụng mặc định";
            button3.Click += button3_Click;
            // 
            // button1
            // 
            button1.Location = new Point(657, 230);
            button1.Name = "button1";
            button1.Size = new Size(115, 30);
            button1.TabIndex = 13;
            button1.Text = "Chọn thư mục";
            button1.Click += button1_Click;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Location = new Point(24, 239);
            label2.Name = "label2";
            label2.Size = new Size(101, 15);
            label2.TabIndex = 11;
            label2.Text = "DownloadPathBill";
            // 
            // txtDownloadPathBill
            // 
            txtDownloadPathBill.Location = new Point(200, 235);
            txtDownloadPathBill.Name = "txtDownloadPathBill";
            txtDownloadPathBill.Size = new Size(440, 23);
            txtDownloadPathBill.TabIndex = 12;
            // 
            // lblApiKey
            // 
            lblApiKey.AutoSize = true;
            lblApiKey.Location = new Point(24, 30);
            lblApiKey.Name = "lblApiKey";
            lblApiKey.Size = new Size(91, 15);
            lblApiKey.TabIndex = 0;
            lblApiKey.Text = "API Key (Bearer)";
            // 
            // txtApiKey
            // 
            txtApiKey.Location = new Point(200, 26);
            txtApiKey.Name = "txtApiKey";
            txtApiKey.Size = new Size(440, 23);
            txtApiKey.TabIndex = 1;
            // 
            // lblAccountId
            // 
            lblAccountId.AutoSize = true;
            lblAccountId.Location = new Point(24, 70);
            lblAccountId.Name = "lblAccountId";
            lblAccountId.Size = new Size(75, 15);
            lblAccountId.TabIndex = 2;
            lblAccountId.Text = "x-account-id";
            // 
            // txtAccountId
            // 
            txtAccountId.Location = new Point(200, 66);
            txtAccountId.Name = "txtAccountId";
            txtAccountId.Size = new Size(440, 23);
            txtAccountId.TabIndex = 3;
            // 
            // lblAccessToken
            // 
            lblAccessToken.AutoSize = true;
            lblAccessToken.Location = new Point(24, 110);
            lblAccessToken.Name = "lblAccessToken";
            lblAccessToken.Size = new Size(124, 15);
            lblAccessToken.TabIndex = 4;
            lblAccessToken.Text = "access-token (Cookie)";
            // 
            // txtAccessToken
            // 
            txtAccessToken.Location = new Point(200, 106);
            txtAccessToken.Name = "txtAccessToken";
            txtAccessToken.Size = new Size(440, 23);
            txtAccessToken.TabIndex = 5;
            // 
            // lblUploadUrl
            // 
            lblUploadUrl.AutoSize = true;
            lblUploadUrl.Location = new Point(24, 150);
            lblUploadUrl.Name = "lblUploadUrl";
            lblUploadUrl.Size = new Size(69, 15);
            lblUploadUrl.TabIndex = 6;
            lblUploadUrl.Text = "Upload URL";
            // 
            // txtUploadUrl
            // 
            txtUploadUrl.Location = new Point(200, 146);
            txtUploadUrl.Name = "txtUploadUrl";
            txtUploadUrl.Size = new Size(720, 23);
            txtUploadUrl.TabIndex = 7;
            // 
            // lblGenerateUrl
            // 
            lblGenerateUrl.AutoSize = true;
            lblGenerateUrl.Location = new Point(24, 190);
            lblGenerateUrl.Name = "lblGenerateUrl";
            lblGenerateUrl.Size = new Size(78, 15);
            lblGenerateUrl.TabIndex = 8;
            lblGenerateUrl.Text = "Generate URL";
            // 
            // txtGenerateUrl
            // 
            txtGenerateUrl.Location = new Point(200, 186);
            txtGenerateUrl.Name = "txtGenerateUrl";
            txtGenerateUrl.Size = new Size(720, 23);
            txtGenerateUrl.TabIndex = 9;
            // 
            // btnSaveConfig
            // 
            btnSaveConfig.Location = new Point(200, 291);
            btnSaveConfig.Name = "btnSaveConfig";
            btnSaveConfig.Size = new Size(160, 34);
            btnSaveConfig.TabIndex = 10;
            btnSaveConfig.Text = "Update (Save)";
            btnSaveConfig.Click += btnSaveConfig_Click;
            // 
            // pollTimer
            // 
            pollTimer.Interval = 5000;
            pollTimer.Tick += pollTimer_Tick;
            // 
            // elapsedTimer
            // 
            elapsedTimer.Interval = 1000;
            elapsedTimer.Tick += elapsedTimer_Tick;
            // 
            // animTitleTimer
            // 
            animTitleTimer.Interval = 20;
            // 
            // MainForm
            // 
            AutoScaleMode = AutoScaleMode.Inherit;
            ClientSize = new Size(1180, 920);
            ControlBox = false;
            Controls.Add(tabs);
            FormBorderStyle = FormBorderStyle.FixedToolWindow;
            Name = "MainForm";
            SizeGripStyle = SizeGripStyle.Hide;
            Text = "Wan2.2 Animate Tool";
            Load += MainForm_Load;
            Shown += MainForm_Shown;
            tabs.ResumeLayout(false);
            tabCreate.ResumeLayout(false);
            tabCreate.PerformLayout();
            grpStatus.ResumeLayout(false);
            grpStatus.PerformLayout();
            grpOutput.ResumeLayout(false);
            grpOutput.PerformLayout();
            grpPrompt.ResumeLayout(false);
            grpPrompt.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numSeed).EndInit();
            grpVideo.ResumeLayout(false);
            grpVideo.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)webView).EndInit();
            grpImage.ResumeLayout(false);
            grpImage.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)picPreview).EndInit();
            headerPanel.ResumeLayout(false);
            headerPanel.PerformLayout();
            BillHistoryTab.ResumeLayout(false);
            panelTop.ResumeLayout(false);
            panelTop.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)numPageSize).EndInit();
            ((System.ComponentModel.ISupportInitialize)grid).EndInit();
            tabSettings.ResumeLayout(false);
            tabSettings.PerformLayout();
            ResumeLayout(false);
        }

        private System.Windows.Forms.TabControl tabs;
        private System.Windows.Forms.TabPage tabCreate;
        private System.Windows.Forms.Panel headerPanel;
        private System.Windows.Forms.Label lblBalance;
        private System.Windows.Forms.GroupBox grpImage;
        private System.Windows.Forms.TextBox txtImagePath;
        private System.Windows.Forms.Button btnBrowseImage;
        private System.Windows.Forms.PictureBox picPreview;
        private System.Windows.Forms.Button btnUploadImage;
        private System.Windows.Forms.Label lblImageUploadedTitle;
        private System.Windows.Forms.TextBox txtImageUploadedUrl;
        private System.Windows.Forms.Label lblUploadImageStatus;
        private System.Windows.Forms.GroupBox grpVideo;
        private System.Windows.Forms.TextBox txtVideoPath;
        private System.Windows.Forms.Button btnBrowseVideo;
        private Microsoft.Web.WebView2.WinForms.WebView2 webView;
        private System.Windows.Forms.Button btnReplay;
        private System.Windows.Forms.Button btnUploadVideo;
        private System.Windows.Forms.Label lblVideoUploadedTitle;
        private System.Windows.Forms.TextBox txtVideoUploadedUrl;
        private System.Windows.Forms.Label lblUploadVideoStatus;
        private System.Windows.Forms.GroupBox grpPrompt;
        private System.Windows.Forms.TextBox txtPrompt;
        private System.Windows.Forms.Label lblSeedTitle;
        private System.Windows.Forms.NumericUpDown numSeed;
        private System.Windows.Forms.Button btnClear;
        private System.Windows.Forms.Button btnGenerate;
        private System.Windows.Forms.GroupBox grpOutput;
        private System.Windows.Forms.TextBox txtGenerateResponse;
        private System.Windows.Forms.Label lblVideoUrlTitle;
        private System.Windows.Forms.TextBox txtOutputVideoUrl;
        private System.Windows.Forms.Button btnDownloadAndOpen;
        private System.Windows.Forms.GroupBox grpStatus;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.ProgressBar prgStatus;
        private System.Windows.Forms.Label lblElapsed;
        private System.Windows.Forms.TabPage tabSettings;
        private System.Windows.Forms.Label lblApiKey;
        private System.Windows.Forms.TextBox txtApiKey;
        private System.Windows.Forms.Label lblAccountId;
        private System.Windows.Forms.TextBox txtAccountId;
        private System.Windows.Forms.Label lblAccessToken;
        private System.Windows.Forms.TextBox txtAccessToken;
        private System.Windows.Forms.Label lblUploadUrl;
        private System.Windows.Forms.TextBox txtUploadUrl;
        private System.Windows.Forms.Label lblGenerateUrl;
        private System.Windows.Forms.TextBox txtGenerateUrl;
        private System.Windows.Forms.Button btnSaveConfig;
        private System.Windows.Forms.Timer pollTimer;
        private System.Windows.Forms.Timer elapsedTimer;
        private Label lblRuntitle;
        private System.Windows.Forms.Timer animTitleTimer;
        private Label label1;
        private TabPage BillHistoryTab;
        private Panel panelTop;
        private Label lblPageSize;
        private NumericUpDown numPageSize;
        private Button btnPrev;
        private Button btnNext;
        private Button btnReset;
        private Label lblPage;
        private Label lblTotal;
        private DataGridView grid;
        private Label label2;
        private TextBox txtDownloadPathBill;
        private Button button1;
        private Button button2;
        private Button button3;
        private Button button4;
        private Button button5;
    }
}